### ISSUE TITLE
I got a error. Please help me!

### ISSUE THREAD

**Issue by SeungHeeHan** [eshapard/AnkiHRPG#10] opened 2016-05-03 23:26 UTC
Traceback (most recent call last):
  File "G:\Documents\Anki\addons\Anki_HRPG.py", line 83, in setup
    hrpg_decks = config['decks']
KeyError: 'decks'

and

Traceback (most recent call last):
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.webview", line 21, in link
  File "G:\Documents\Anki\addons\play_button.py", line 60, in review_link_handler_wrapper
    original_review_link_handler(reviewer, url)
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.reviewer", line 323, in _linkHandler
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/anki.hooks", line 58, in repl
  File "G:\Documents\Anki\addons\Anki_HRPG.py", line 232, in card_answered
    hrpg_realtime()  
  File "G:\Documents\Anki\addons\Anki_HRPG.py", line 158, in hrpg_realtime
    get_user()
  File "G:\Documents\Anki\addons\Anki_HRPG.py", line 122, in get_user
    response = json.load(urllib2.urlopen(user_object))
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/urllib2", line 126, in urlopen
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/urllib2", line 406, in open
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/urllib2", line 519, in http_response
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/urllib2", line 444, in error
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/urllib2", line 378, in _call_chain
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/urllib2", line 527, in http_error_default
urllib2.HTTPError: HTTP Error 401: Unauthorized
Traceback (most recent call last):
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.webview", line 21, in link
  File "G:\Documents\Anki\addons\play_button.py", line 60, in review_link_handler_wrapper
    original_review_link_handler(reviewer, url)
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/aqt.reviewer", line 323, in _linkHandler
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/anki.hooks", line 58, in repl
  File "G:\Documents\Anki\addons\Anki_HRPG.py", line 232, in card_answered
    hrpg_realtime()  
  File "G:\Documents\Anki\addons\Anki_HRPG.py", line 158, in hrpg_realtime
    get_user()
  File "G:\Documents\Anki\addons\Anki_HRPG.py", line 122, in get_user
    response = json.load(urllib2.urlopen(user_object))
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/urllib2", line 126, in urlopen
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/urllib2", line 406, in open
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/urllib2", line 519, in http_response
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/urllib2", line 444, in error
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/urllib2", line 378, in _call_chain
  File "C:\cygwin\home\dae\win\build\pyi.win32\anki\outPYZ1.pyz/urllib2", line 527, in http_error_default
urllib2.HTTPError: HTTP Error 401: Unauthorized

**Comment by eshapard** [comment] 2016-05-04 06:22
Which version of the add-on is this? It will say at the top of the addon.

Would you post the contents of your .habitrpg.conf file? You can just replace your user-id and token with #####s or something.

**Comment by eshapard** [comment] 2016-05-04 06:29
I think I may have found the error. Try deleting lines 83 and 84. They are the lines that mention hrpg_decks = config['decks']  and hrpg_timeboxes = config['timeboxes']

These are both settings that were in the old config file, but not used anymore.

**Comment by eshapard** [comment] 2016-05-04 06:41
Also, I just posted a version 1.2 on github. Try this version, it has better error handling.

**Comment by SeungHeeHan** [comment] 2016-05-04 07:47
Thank you very much but it takes a lot of time to sync data. Is that normal?
Best regards,

**Comment by SeungHeeHan** [comment] 2016-05-04 07:57
And every card I learn, one windows appears say "...well done..". It also takes times to progress. How can I solve this problem?
Thanks again.

**Comment by eshapard** [comment] 2016-05-04 15:58
Syncing should not be affected by the plugin. The new version does not attach itself to the syncing process.

You shouldn't be seeing a window every time you answer a card. Please print the full text of the message.

Try deleting the .habitrpg.conf file from your addons directory and re-entering your userid and api-token through Tools >> SetUp HabitRPG

**Comment by eshapard** [comment] 2016-05-04 16:02
Also, did you edit the reward schedule variables in the plugin?

**Comment by eshapard** [comment] 2016-05-04 16:03
Oh, also make sure your plugin directory does not contain any older versions of the plugin. Maybe delete them all and reinstall the newest one.

**Comment by SeungHeeHan** [comment] 2016-05-04 21:47
I reinstall the version updated in anki addons and deleted .habitrpg.conf file. But it isn't worked. I try to edit the plugin by copying and pasting your code version 1.2 on github. And that's ok. Also I do want to edit the reward schedule variables in the plugin but I don't know how to do this. I want to study at least 100 cards and then the message "Huzzah! You get points! Well Done Seung Hee! + 0 gold" will be showed up. I hope you can teach me to do it. 
Thank you and have a good day eshapard!

**Comment by eshapard** [comment] 2016-05-04 23:27
I need more to go on then "But it isn't working". What error message are you getting and when? What isn't happening?

Please post the contents of your .habitrpg.conf file. You can replace your userid and token with #### characters or something so that no can see them.

To edit the settings of the addon, go to Tools >> Addons >> ankihrpg >> Edit...

Change hrpg_sched to 100
Change hrpg_threshold to 85
That should give you close to the behavior you want.

**Comment by SeungHeeHan** [comment] 2016-05-04 23:33
{"tries": 0, "score": 0, "user": "1111111111", "token": "111111111111111111"}
How quickly you answer!

**Comment by eshapard** [comment] 2016-05-05 00:29
OK, What error message are you getting? What's not working?

Try your user-id and token at: https://habitica.com/static/api

Try to run User >> Get /user/tasks >> Try It Out!
If that doesn't work, then the problem is your user id and token.

**Comment by eshapard** [comment] 2016-05-05 00:31
Oh, and you should set hrpg_step to 10 if you've changed hrpg_sched to 100.

**Comment by SeungHeeHan** [comment] 2016-05-06 01:55
I did as you say and it seem to be fine in my desktop. I finally have what I want. However, when I sync my data, It is not sync data to habitica. 

I Try user-id and token at: https://habitica.com/static/api

Try to run User >> Get /user/tasks >> Try It Out!
It returned:
  "err": "No user found."

Before that, I deleted config file and enter Id and token several times.

Please show me the way to make it out. Thank you for your consideration.

**Comment by eshapard** [comment] 2016-05-06 04:04
OK, if your user-id and token are not working at the api site that I showed you, then the problem is your user-id and token.

If you're logged in to habitica, go to this page: https://habitica.com/#/options/settings/api

It should show your user-id and token. These are what you use to configure the plugin. If you copy and paste them, make sure you don't accidentally copy/paste any blank spaces before or after the numbers.

Test them out first at: https://habitica.com/static/api
Try to run User >> Get /user/tasks >> Try It Out! again.

If that works, then use that user-id and token to configure the addon.

**Comment by SeungHeeHan** [comment] 2016-05-06 07:23
I've just done exactly as you said and my habitica account have a new habit called "Anki Points". Right now I don't know whether that work or not because you know I have to study at least 100 cards to see its effect. No, 120 exactly. 

I like "progress bar" idea so much. It's so motivated. But I like even more if you create "time bar". I have important exams to take so time, process and accuration (precise) are life-or-death factors. If I takes too much time to study 120 card, that doesn't make any sense. Somehow, my character's life is taken by myself. T_T. I just want to know how much time left I have.

I know It's difficult to make something new. That's only an idea.

Thank you for your time. I really appreciate your help until now.
Best regard,
Seung Hee Han

**Comment by eshapard** [comment] 2016-05-06 16:13
OK, "Anki Points" is the habit that the addon creates, so it sounds like you got it working.

In Anki's preferences, you can choose to set a "timebox". If you set it to 15 minutes, then you'll get a pop-up after you've studied for 15 minutes telling you that you've reached your goal of 15 minutes. But no countdown. You could always just set a timer (either on your computer, or a kitchen timer) so that you have this countdown of how long you have before you meet your goal.

It sounds like this issue is resolved, so I'll close this thread soon.

**Comment by SeungHeeHan** [comment] 2016-05-07 00:01
I want my deck view look like that
![image](https://cloud.githubusercontent.com/assets/19177530/15088675/5a1ae448-1421-11e6-8864-4dc5349b82b8.png)
How can I find this addons. I tried but fail.
Hope you can help.
Best regards,

**Comment by eshapard** [comment] 2016-05-07 00:23
I've never seen that one. Try asking on reddit.com/r/Anki

**Comment by SeungHeeHan** [comment] 2016-05-07 09:33
Thank you!
See you again!
"Something old, something new, something borrowed, something blue"
Wish you have such "something" everyday ^^ eshapard !!~ 
...(I can sing(ing) 'til I hear you say "Thank you":)

**Closed** 2016-05-11 16:02 UTC
